---
engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.js"
  - "**.php"
exclude_paths:
- tests/
- js/ace
- js/select2