# whitelist
branches:
  only:
    - wporg

language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

cache:
- bundler
- apt

addons:
  apt:
    packages:
    - ruby

install: gem install nyx

script:
    - nyx check:php .